### PR TITLE
allow initialize/clean to be run in parallel

### PR DESCRIPTION
**Pull request by bendavies**
Hi,

This allows specifying `-j` to Make, so we can parallelize starting and stopping docker.

Should speed up local dev and CI on GitHub Actions.

### CODE REVIEW

**Comment by bendavies** [comment]
fails because of timing issue starting two containers called `async_aws_s3` used by Service/S3 and Flysystem. I can fix if there is interested in pursuing this.

the negative is the high cognitive load of the Makefile after these changes.

**Comment by jderusse** [comment]
Go ahead I like it. I was thinking about opening an issue for this.

**Comment by Nyholm** [comment]
Awsome. Thank you!

**Comment by bendavies** [comment]
this can be extended to downloading deps in parallel which is also slow in CI

**Comment by bendavies** [comment]
good for merge. can iterate on other steps.

**Comment by jderusse** [comment]
I've a issue when running it on my local machine (not I want to run test on Root repository. I dont install dependencies on each sub part
```
$ make test -j 1
make -C src/Integration/Flysystem/S3 test
make[1]: Entering directory '/data/oss/aws/src/Integration/Flysystem/S3'
docker pull asyncaws/testing-s3
Using default tag: latest
latest: Pulling from asyncaws/testing-s3
Digest: sha256:7f1735482ca7924be65aae0e9a8bb2c0355965b2539f010390a1739e85341ef7
Status: Image is up to date for asyncaws/testing-s3:latest
docker.io/asyncaws/testing-s3:latest
docker start async_aws_flysystem_s3 || docker run -d -p 4570:4569 --name async_aws_flysystem_s3 asyncaws/testing-s3
async_aws_flysystem_s3
./vendor/bin/simple-phpunit
make[1]: ./vendor/bin/simple-phpunit: Command not found
make[1]: *** [Makefile:9: test] Error 127
make[1]: Leaving directory '/data/oss/aws/src/Integration/Flysystem/S3'
make: *** [Makefile:7: src/Integration/Flysystem/S3] Error 2
```

> make[1]: ./vendor/bin/simple-phpunit: Command not found

I believe it try to run phpunit IN Flysystem sub project

**Comment by bendavies** [comment]
Thanks I'll take a looks

**Comment by bendavies** [comment]
so `test` is calling `initialize` which calls `start-docker` in all the component subdirs, but then `test` is executued in the subdir as you note.
I'm not sure how to fix that right now.

like i said above:
> the negative is the high cognitive load of the Makefile after these changes.
Maybe this complication is not worth it at the moment :-/

**Comment by bendavies** [comment]
@jderusse fixed, but it does become more unreadable 😆

**Pull request merged**
