### PR TITLE
add `putuserpolicy`, `deleteuserpolicy`, `createservicespecificcredential` to `IAM` client

### PR DESCRIPTION
**Pull request by nealio82**
* Add generated `PutUserPolicy` method
* Add generated `DeleteUserPolicy` method
* Add generated `CreateServiceSpecificCredential` method
* Fill in tests
* Add documentation

### CODE REVIEW

**Comment by nealio82** [comment]
```
#  One of two things are wrong here:
#   1) You have modified generated code.
#   2) You have modified the code generator and not regenerated the code.
```

Neither of these things are true 🤔 

```
diff --git a/src/Service/Iam/src/Enum/StatusType.php b/src/Service/Iam/src/Enum/StatusType.php
index 54f0223..9cddacc 100644
--- a/src/Service/Iam/src/Enum/StatusType.php
+++ b/src/Service/Iam/src/Enum/StatusType.php
@@ -3,8 +3,7 @@
 namespace AsyncAws\Iam\Enum;
 
 /**
- * The status of the service-specific credential. `Active` means that the key is valid for API calls, while `Inactive`
- * means it is not.
+ * The status of the access key. `Active` means that the key is valid for API calls, while `Inactive` means it is not.
  */
```

Does this mean that the Enum's being re-used and there's a race condition in generating the comment at the top?

**Comment by jderusse** [comment]
> ```
> #  One of two things are wrong here:
> #   1) You have modified generated code.
> #   2) You have modified the code generator and not regenerated the code.
> ```
> 
> Neither of these things are true thinking
> 
> ```
> diff --git a/src/Service/Iam/src/Enum/StatusType.php b/src/Service/Iam/src/Enum/StatusType.php
> index 54f0223..9cddacc 100644
> --- a/src/Service/Iam/src/Enum/StatusType.php
> +++ b/src/Service/Iam/src/Enum/StatusType.php
> @@ -3,8 +3,7 @@
>  namespace AsyncAws\Iam\Enum;
>  
>  /**
> - * The status of the service-specific credential. `Active` means that the key is valid for API calls, while `Inactive`
> - * means it is not.
> + * The status of the access key. `Active` means that the key is valid for API calls, while `Inactive` means it is not.
>   */
> ```
> 
> Does this mean that the Enum's being re-used and there's a race condition in generating the comment at the top?

AWS has a weird way to add comments on the objects.
Actually,m the comment is set on the relation caller -> callee. That's why sometimes the comment changes when adding a new method. 
To fix the issue, run `generate --all` to make the CI happy

**Comment by nealio82** [comment]
@jderusse passing now :)

Kinda frustrating that Localstack doesn't support `CreateServiceSpecificCredential` though :/

**Review by jderusse — APPROVED** [review]

**Comment by jderusse** [comment]
thanks you @nealio82

**Pull request merged**
