### PR TITLE
Implement waiters - sync

### PR DESCRIPTION
**Pull request by jderusse**
Regarding the User Experience. I hesitate between

Current Impl:
```php
$sqsClient->queueExists(['QueueName' => 'fooBar']); // bool
$sqsClient->waitForQueueExists(['QueueName' => 'fooBar'], $delay, $maxAttempts); // void
```

and Idea
```php
$checker = $sqsClient->queueExists(['QueueName' => 'fooBar']); // Checker
$checker->isSuccessfull(); // bool
$checker->isFailure(); // bool
$checker->wait($delay, $maxAttempts); // void: wait  untill either success, failure, or timeout
$checker->resolve(); // call to internal operation is async itself, which is not possible with my current impl
```

### CODE REVIEW

**Comment by Nyholm** [comment]
I like your idea. It seams cleaner and friendlier.

But I don’t understand the comment about calling resolve()

**Comment by jderusse** [comment]
waiters internally called a method. For instance the waiter `QueueExists` called `GetQueueUrl` and check is the response is 200 or 404.
With my impl, the call to `QueueExists` is synchronous. If we want to be full Async, I should replace my `return bool` by an Object that provide a `resolve` method...

**Comment by Nyholm** [comment]
Fully async FTW!

**Comment by jderusse** [comment]
closed in favor of #156

**Pull request closed without merging**
