### PR TITLE
Add operations in SNS

### PR DESCRIPTION
**Pull request by jderusse**
Thoses operation are required by https://github.com/php-enqueue/enqueue-dev/pull/1046

### CODE REVIEW

**Comment by Nyholm** [comment]
I did a quick review. I think it all looks good. Just make sure to add some tests.

**Comment by jderusse** [comment]
I've added test in input/result based on documentation's output.
I don't find Sns docker image.

do you expect something else?

**Comment by Nyholm** [comment]
Na, this is fine =)

Thank you

**Comment by jderusse** [comment]
Thanks for the review

**Pull request merged**
