### PR TITLE
fix: edge case where aws config file could be a directory

### PR DESCRIPTION
**Pull request by shouze**
I have encountered this issue on github actions

This is weird but I an error with file_get_contents failing.
image

### CODE REVIEW

**Review by jderusse — APPROVED** [review]
Good catch

**Comment by shouze** [comment]
> Good catch

Anyway you could argue: why ~/.aws/credentials is a directory for you? I have to admit this is a very strange edge case, some kind of monster that we've created ourselves :japanese_ogre:.

**Comment by jderusse** [comment]
> > Good catch
> 
> Anyway you could argue: why ~/.aws/credentials is a directory for you? I have to admit this is a very strange edge case, some kind of monster that we've created ourselves .

This kind of things happens when you mount a docker volume to a file and the file does not exists, docker creates a directory

**Comment by shouze** [comment]
> This kind of things happens when you mount a docker volume to a file and the file does not exists, docker creates a directory

oh my, you got me! :wink:

**Pull request merged**
