### PR TITLE
Fixed nullable nested objects

### PR DESCRIPTION
**Pull request by Nyholm**
I found this issue in CloudFormation. 

We have to make sure nested objects work properly.. Im not sure if I broke something in my previous PRs... I probably did.. anyhow. Here is a test so we dont break things in the future.

### CODE REVIEW

**Comment by Nyholm** [comment]
Have a look at https://github.com/async-aws/aws/pull/188/commits/92518290dc62af327ee0f617b47b975da03091ec.
We missed that lists are nested like: 

```xml
<DescribeStacksResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
  <DescribeStacksResult>
    <Stacks>
      <member>
        <Outputs>

`

**Comment by Nyholm** [comment]
> We missed that lists are nested like...

This is not always true. If the ListShape does not have a location name, then we should add `->member`

**Comment by jderusse** [comment]
I think we have the same behavior is see send email for CC addresses.

**Comment by Nyholm** [comment]
Thank you for the review. 

Hm. The SES for SendEmail is not the same. In this PR we are dealing with responses. 

Or did I misunderstand you?

**Comment by jderusse** [comment]
https://docs.aws.amazon.com/fr_fr/ses/latest/APIReference/API_SendEmail.html 
looks for `ReplyToAddresses.member.N`

I didn't take time to dig and investigate in `member` thing. But I think it's related.

**Pull request merged**
