### PR TITLE
Added SQS batch actions

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This PR adds support for the new SQS `ChangeMessageVisibilityBatch`, `DeleteMessageBatch`, `SendMessageBatch` actions.

### CODE REVIEW

**Comment by jderusse** [comment]
I'm about to release a bunch of services (probably this week-end)

Do you think you'll have time to finish this PR?

**Comment by GrahamCampbell** [comment]
Yes, I will do it tonight or tomorrow.

**Comment by GrahamCampbell** [comment]
@jderusse Ready for review now. :)

**Comment by jderusse** [comment]
That's awesome. Thank you very much @GrahamCampbell

**Pull request merged**
