### PR TITLE
Download last metadata version

### PR DESCRIPTION
**Pull request by jderusse**
Fetch the last version from packagist, and download the last AWS Sdk stable version

### CODE REVIEW

**Comment by Nyholm** [comment]
How is the cache cleared? Is it only manual?

What if I:
- clone
- generate
- aws release
- make a PR
- PR will fail because my output does not match generated output

**Comment by jderusse** [comment]
- the call to packagist (to fetch last version) is cached for 5 minutes
- the call to github (to fetch each .json) vary with full URL (which contains the version)

But you're right. If a new version is released in the meantime, the PR could be invalid.

I wonder if the the build should be reproducible (hard coded version) or accurate (dynamically fetch last version).

If you prefer staying reproductible, I'll have a look to the BOT (we talked here https://github.com/async-aws/aws/issues/258) to fetch last version and create a new PR to update the version WDYT?

**Comment by Nyholm** [comment]
> the call to packagist (to fetch last version) is cached for 5 minutes

Good. 

Reproducible is fine. I just wanted to make sure that recurring contributors dont get error because AWS released new versions. 

Im happy to merge

**Comment by jderusse** [comment]
Use hard coded version

**Pull request merged**
