### PR TITLE
Generate ClassName with Uppercase

### PR DESCRIPTION
**Pull request by amenophis**

### CODE REVIEW

**Comment by Nyholm** [comment]
Hm.. It might be this simple. Let's see what CI says =)

**Comment by amenophis** [comment]
@Nyholm All good !

**Comment by jderusse** [comment]
LGTM. Did you tried this patch on your #812 @amenophis ?

**Comment by amenophis** [comment]
Yes, It generates the Status Enum starting with uppercase

**Comment by jderusse** [comment]
Thank you @amenophis

**Pull request merged**
