### PR TITLE
Fix properties not base64 decoded

### LINKED ISSUE #1564: DynamoDB binary value encoding inconsistency
In requests, one passes the raw binary string `['B' => 'foo bar baz']`, but in responses, `->getB()` is base64 encoded. This feels like a bug to me (though will need a major version bump to "fix", so as to not break stuff for people).

### PR DESCRIPTION
**Pull request by jderusse**
fix #1564

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Oooh, it looks like this possibly fixes another issue where by nesting of attributes such as in maps are not transformed?

**Comment by GrahamCampbell** [comment]
Oh, yeh, you mention this in the other issue. ;)

**Comment by GrahamCampbell** [comment]
I had forgotten that I'd also seen this happening with maps before in dynamodb, which was quite annoying, in particular for request retrying using the output of a partial failure from batch write items.

**Comment by hassaan-dev** [comment]
Thank you guys

**Pull request merged**
