### PR TITLE
Make sure we dont have any direct deprecation notices

### PR DESCRIPTION
**Pull request by Nyholm**
This will make the build green... hopefully

### CODE REVIEW

**Comment by Nyholm** [comment]
Wohoo!

The build is green on PHP8

**Comment by jderusse** [comment]
I'm not sure about this one.. Shouldn't we warned when having a (maybe unmaintained) dependency that triggers deprecation?

**Comment by Nyholm** [comment]
We are still warned. See

Screenshot 2020-08-20 at 14 45 33

But the build will not fail. 

The deprecation error is only on PHP8 because Symfony is using `libxml_disable_entity_loader()`

Screenshot 2020-08-20 at 14 46 06

To have the build red because if this is too much. There is nothing we can do about it but fixing the dependency's code or to not use that dependency.

**Comment by jderusse** [comment]
> To have the build red because if this is too much. There is nothing we can do about it but fixing the dependency's code or to not use that dependency.

I made the PR, and it has been merged few days ago. Next release should fix it.

I personally rarely looks hat build logs when the CI is green. I afraid to miss issue with this change.

**Comment by Nyholm** [comment]
That is awesome. But.. should we care so much about an indirect dependency’s deprecation notice?

I guess the build should be red at that dependency too.

**Comment by jderusse** [comment]
yeah that's the question... 
given we only rely on highly maintained dependencies, I guess it's ok then

**Review by jderusse — APPROVED** [review]

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
