### PR TITLE
Fixed broken query string encoding

### PR DESCRIPTION
**Pull request by GrahamCampbell**
`http_build_query` defaults to building strings for form request bodies, not URI query strings. We have to put it into that mode using the 4th param.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Oh, I think the encoding in the V4 signer is also wrong, and only worked because the encoding here was wrong also.

**Comment by GrahamCampbell** [comment]
Probably nobody has noticed before since it would be rare to use a space character in a query string, and may AWS services probably accept the wrong encoding, and since it was encoded wrong both when signing and constructing, the signature was good.

**Comment by GrahamCampbell** [comment]
image
image

**Comment by GrahamCampbell** [comment]
Moving to draft until I have had time to try this out for really realz.

**Comment by GrahamCampbell** [comment]
Many AWS services seem to support the incorrect encoding, though I think not all. This is ready for review now.

**Comment by jderusse** [comment]
the AWS SDK use `PHP_QUERY_RFC3986`. What is the difference with `PHP_QUERY_RFC1738`?

**Comment by GrahamCampbell** [comment]
OK, fixed now. This explains why the signing was working. The query encoding was correct when doing the signing, so when AWS normalized the query string on their side after our incorrect encoding, the signature matched because the correct encoding algorithm was used when we calculated the signature.

**Review by jderusse — APPROVED** [review]

**Pull request merged**
