### PR TITLE
add CodeCommit client with getBranch, getDifferences, getBlob

### PR DESCRIPTION
**Pull request by nealio82**
Add the `CodeCommit` client with generated methods for `getBranch()`, `getDifferences()`, and `getBlob()`

^^ This is the minimum you will need to be able to generate diffs between commits or branches

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I think this needs adding to the symfony integration, too (i also think that is missing from the contributing docs :P).

**Comment by nealio82** [comment]
@GrahamCampbell  Yup, I followed the docs at https://async-aws.com/contribute/generate.html#creating-a-new-client, which didn't mention the SF integration. I assume you mean to add the client class to here? https://github.com/async-aws/symfony-bundle/blob/master/src/DependencyInjection/AwsPackagesProvider.php

**Comment by jderusse** [comment]
I believe the copy/paste failed at some point: Most of the files (`CHANGELOG.md`, `ci.yml`, `.gitattributes`, `LICENSE`) are empty

**Comment by nealio82** [comment]
Yeah, I noticed that but I didn't question it as they were generated 🤦‍♂️ I'll copy them over from an existing example

**Comment by nealio82** [comment]
@jderusse I _think_ this is done now - is there anything else you need me to do?

I noticed that there's the Symfony integration within this repo as well (`AwsPackagesProvider` class) - is it this one or the separate Symfony bundle repo @GrahamCampbell was referring to earlier? 🤔

**Comment by jderusse** [comment]
thank you @nealio82

**Pull request merged**
