### PR TITLE
Add support for Laravel 8

### PR DESCRIPTION
**Pull request by IonBazan**
This PR simply adds support for Laravel 8 and adds PHP 8.0 to build matrix.

### CODE REVIEW

**Comment by Nyholm** [comment]
Cool. Thank you. 

Have the integrations been tested on Laravel 8? Do we need to keep supporting Laravel 6? Im not sure about the release cycle.

**Comment by IonBazan** [comment]
@Nyholm I didn't have much time to test the integrations on Laravel 8 except for `Filesystem` but I think there were no big changes in other components too. I would suggest to keep Laravel 6 support for now as it's LTS version: https://laravel.com/docs/6.x/releases#support-policy.

**Review by Nyholm — APPROVED** [review]
> I would suggest to keep Laravel 6 support for now as it's LTS version

Okey. Thank you. I didint know. 

>  I didn't have much time to test the integrations on Laravel 8 except for Filesystem but I think there were no big changes in other components too.

So Filesystem is properly tested, right? Or it works for you?

> Test suites are passing on L8 so I think it's alright 👍🏻

I hope you are correct =)

**Review by chalasr — APPROVED** [review]

**Comment by IonBazan** [comment]
@Nyholm Yes, Filesystem integration seems to be working fine with v8.

**Comment by IonBazan** [comment]
@Nyholm Can you tag a new release or are we waiting for some other PRs?

**Comment by Nyholm** [comment]
Sure. I'll make sure to get around to it today.

**Pull request merged**
