### PR TITLE
[CI] Add parameters to "composer init"

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Review by jderusse — APPROVED** [review]
I'm not sure to understand what this PR solves

**Comment by Nyholm** [comment]
Look at the CI on the first commit. It is red. So is master. 

I think composer added a requirement on `composer init` that you needed to add the `--name` parameter.

**Comment by jderusse** [comment]
thank you

**Comment by Nyholm** [comment]
Thank yuo for merging

**Pull request merged**
