### PR TITLE
Move StreamableBody to AsyncAws\Core\Stream

### PR DESCRIPTION
**Pull request by Nyholm**
I also renamed: 
- `StreamableBody` to `ResponseBodyStream`
- `StreamableBodyInterface` to `ResultStream`

### CODE REVIEW

**Comment by Nyholm** [comment]
Should we rename `Stream` to `InputStream?`

**Comment by jderusse** [comment]
Yes, I think we should not mix both (because all instances in `Stream` are related to the `Stream` interface) That could be confusion.

I vote for `InputStream` or `RequestBodyStream` or `RequestStream` or `BodyStream`

**Comment by Nyholm** [comment]
If you don’t want them in the same namespace. What namespace do you suggest for the ResultStream?

**Comment by jderusse** [comment]
What's about `RequestStream`+`ResultStream` or `Stream/Request`+`Stream/Result`
`Stream` interface should should be renamed into `RequestStream` for consistency

**Comment by Nyholm** [comment]
Im happy with RequestStream+ResultStream. 

Is that putting them in the same namespace?

**Pull request merged**
