### PR TITLE
Use fixed version of Psalm & PHP-cs-fixer

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by Nyholm** [comment]
Blocked by https://github.com/async-aws/aws/pull/786

**Comment by bendavies** [comment]
how does that work? i can't see any releases or how the version is respected in https://github.com/psalm/psalm-github-actions

**Comment by bendavies** [comment]
oh i see, pushed to dockerhub

**Comment by Nyholm** [comment]
Yeah, but https://github.com/psalm/psalm-github-actions/issues/15 is still blocking. I added a CI script to push tagged releases but we are missing secrets. 

We need to wait for @muglug to add those.

**Comment by Nyholm** [comment]
Thank you. 

This PR is now ready for review

**Review by jderusse — APPROVED** [review]

**Comment by Nyholm** [comment]
Thank you for the reviews.

**Pull request merged**
