### PR TITLE
Add confirm sign up method

### PR DESCRIPTION
**Pull request by nealio82**
Add `confirmSignUp` to the `CognitoIdentityProvider` client

### CODE REVIEW

**Comment by nealio82** [comment]
Is anyone able to shed any light on why `Flysystem/S3` might fail? I haven't touched it in this PR. Is it flaky? 🤔 

`Error: src/Integration/Flysystem/S3 failed`

**Comment by nealio82** [comment]
Oh, segfault. How to fix? 🤔 

```
src/Integration/Flysystem/S3
  PHPUnit 9.5.20 #StandWithUkraine
  
  Testing 
  /home/runner/work/_temp/5c0d5b0c-bcc1-4493-9f02-3a230b7f14ef.sh: line 5:  7367 Segmentation fault      (core dumped) ./vendor/bin/simple-phpunit -c ./$COMPONENT 2>&1
```

**Comment by jderusse** [comment]
this is a default on PHP 8.2 which is not related to your change. You can ignore it

**Review by jderusse — APPROVED** [review]

**Comment by jderusse** [comment]
thank you @nealio82

**Pull request merged**
