### PR TITLE
[Core] Prepare for 1.5 release

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Review by jderusse — APPROVED** [review]

**Review by chalasr — CHANGES_REQUESTED** [review]
The composer branch-alias needs to be updated, right? looks like we need some automation :)

**Comment by Nyholm** [comment]
I will be happy to add that automation =)

I've got some questions for the automation:

What is the rule? When we release 1.5.0, then we should update the branch alias to: 

```json
        "branch-alias": {
            "dev-master": "1.6-dev"
        }
```
Right?

---------

I've heard people saying that the branch alias should be updated only when new changes has been added after 1.5.0 is tagged. 

-------

Is it important that the new branch alias is changed before we tag 1.5.0?

**Comment by chalasr** [comment]
From my understanding and looking at Symfony, the branch alias should indeed be updated right after the tag creation. 
This one should have been changed to `1.5-dev` when 1.4 was released, and should change to `1.6-dev` once 1.5 released.

**Review by chalasr — APPROVED** [review]
Ready to go!

**Comment by Nyholm** [comment]
Cool. I'll make sure to automate that. =)

**Review by jderusse — APPROVED** [review]

**Pull request merged**
