### PR TITLE
Add support for endpoint discovery in core

### PR DESCRIPTION
**Pull request by jderusse**
Followup #1239

This PR add support of endpoint discovery in core.
It could be leverage by client, thank to new parameter in RequestContext and implementing the underlying protected method

### CODE REVIEW

**Comment by stof** [comment]
@jderusse the timestream Endpoint objects don't actually implement the EndpointInterface of the core. So this interface looks useless.

**Comment by stof** [comment]
And it looks like `getDiscoveredEndpoint` ignores the method arguments when finding an endpoint through discovery. Is it expected ?

**Comment by jderusse** [comment]
> it looks like getDiscoveredEndpoint ignores the method arguments

Which argument?

**Comment by jderusse** [comment]
> `$uri` and `$query`

You're right. 
Hopefully, it did not have any impact on our single client using discovered endpoint (DynamoDb) because all implemented endpoints used `uri = /` uri and `query = []`.

Fixed in https://github.com/async-aws/aws/pull/1415

**Pull request merged**
