### PR TITLE
Adding docs for Localstack

### PR DESCRIPTION
**Pull request by reypm**
- Adding Localstack configuration

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. 

Let's keep this PR as a discussion for whatever issues that may occur and we can all help suggesting changes and try out things.

**Comment by Nyholm** [comment]
How is it going? Have you managed to spend some time with this?

**Comment by reypm** [comment]
> How is it going? Have you managed to spend some time with this?

Nope, I have not had the time to work on this 👎  ... probably during weekend I am afraid but I will try to help since I have to setup a new project just for this

**Comment by reypm** [comment]
@Nyholm I have been really busy lately and haven't had the time yet to move a finger regarding this ... keep this open a little more and I will look for a free time in order to get this sorted. Apologies

**Comment by Nyholm** [comment]
Hey. 
How is it going? Do you need any help with this?

**Comment by Nyholm** [comment]
Im closing this for now. 

Feel free to reopen the PR if you do some work on it.

**Pull request closed without merging**
