### PR TITLE
Allow Symfony 7

### PR DESCRIPTION
**Pull request by nicolas-grekas**

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
@jderusse @Nyholm or any other maintainer, could you please have a look at this PR? It's on the critical path to unlock the CI to prepare Symfony 7 :pray:

**Comment by jderusse** [comment]
> @jderusse @Nyholm or any other maintainer, could you please have a look at this PR? It's on the critical path to unlock the CI to prepare Symfony 7 pray

Would be great to fix the deprecations (ie, replace `assertCount(0, $fooBar)` by` assertEmpty($fooBar)` or `assertCount(0, [...$fooBar])`)

**Review by Nyholm — APPROVED** [review]
Isn't the deprecation warnings from PHPUnit?

**Comment by jderusse** [comment]
> Isn't the deprecation warnings from PHPUnit?

It's triggered by PhpUnit because of our code:

When we call `self::assertCount(0, $result->getStackEvents())` here https://github.com/async-aws/aws/blob/11379d8d430fe0f938e9832f092b329aa966cfa1/src/Service/CloudFormation/tests/Integration/CloudFormationClientTest.php#L48
The method `$result->getStackEvents()` is a generator https://github.com/async-aws/aws/blob/11379d8d430fe0f938e9832f092b329aa966cfa1/src/Service/CloudFormation/src/Result/DescribeStackEventsOutput.php#LL52C14-L52C14
Which is no more allowed https://github.com/sebastianbergmann/phpunit/blob/46739478930289fa955fe4697688bae921a2674a/src/Framework/Assert.php#L236-L238

**Comment by nicolas-grekas** [comment]
Deprecations fixed, CI green.

**Comment by jderusse** [comment]
thanks :heart:

**Pull request merged**
