### PR TITLE
Fix the doc markup for authentication

### PR DESCRIPTION
**Pull request by stof**

### CODE REVIEW

**Review by jderusse — APPROVED** [review]

**Review by jderusse — APPROVED** [review]

**Comment by jderusse** [comment]
tanks

**Comment by stof** [comment]
@jderusse the new build happened in https://github.com/async-aws/website/commit/b974ec98baea4df97774c584f8e513cb6dab1462 but the website still shows the old content. Is there something broken with the deployment process ?

**Comment by jderusse** [comment]
@Nyholm would you mind to have a look?

**Comment by Nyholm** [comment]
Hm... The netify build log gave me: 

```
  The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.
```

¯\\_(ツ)_/¯

I'll try to rebuild now

**Comment by Nyholm** [comment]
Updated https://async-aws.com/authentication/hard-coded.html

**Pull request merged**
